services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: paul-martin-nevot_app
    restart: always
    ports:
      - "${PORT:-3000}:3000" # Maps host port 50013 to container port 3000
    environment:
      - NODE_ENV=production
      - PORT=3000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
